// <auto-generated />
using System;
using System.Collections.Generic;
using LearnEnglishWebApp.Data;
using LearnEnglishWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnEnglishWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnEnglishWebApp.Models.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.CollectionWord", b =>
                {
                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserWordId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CollectionId", "UserWordId");

                    b.HasIndex("UserWordId");

                    b.ToTable("CollectionsWords");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.Dictionary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .HasColumnType("text");

                    b.Property<string>("DifficultyLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.PrimitiveCollection<string>("Examples")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevel");

                    b.HasIndex("Word")
                        .IsUnique();

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.GrammarTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("GrammarTopicId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("TestKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GrammarTopicId");

                    b.HasIndex("TestKey")
                        .IsUnique();

                    b.HasIndex("Level", "OrderIndex");

                    b.ToTable("GrammarTests");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.GrammarTopic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContentKey")
                        .IsUnique();

                    b.HasIndex("Level", "OrderIndex");

                    b.ToTable("GrammarTopics");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.TestResult", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TestType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<List<TestAnswerDetail>>("AnswerDetails")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSpentSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("WrongAnswers")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "TestType", "TestId", "AttemptNumber");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("IsPassed");

                    b.HasIndex("TestType");

                    b.HasIndex("TestType", "TestId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.UserGrammarProgress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("GrammarTopicId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GrammarTopicId");

                    b.HasIndex("GrammarTopicId");

                    b.ToTable("UserGrammarProgress");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.UserVocabProgress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "LessonId");

                    b.HasIndex("LessonId");

                    b.ToTable("UserVocabProgresses");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.UserWord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContextSentence")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("WordId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WordId");

                    b.HasIndex("UserId", "WordId")
                        .IsUnique();

                    b.ToTable("UsersWords");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.VocabLesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.PrimitiveCollection<string>("VocabularyWordIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ContentKey")
                        .IsUnique();

                    b.HasIndex("Level", "OrderIndex");

                    b.ToTable("VocabLessons");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.VocabTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PassingScore")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer");

                    b.Property<string>("TestKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TimeLimitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("VocabLessonId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TestKey")
                        .IsUnique();

                    b.HasIndex("VocabLessonId");

                    b.HasIndex("Level", "OrderIndex");

                    b.ToTable("VocabTests");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.Collection", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.CollectionWord", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.Collection", "Collection")
                        .WithMany("CollectionWords")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnEnglishWebApp.Models.UserWord", "UserWord")
                        .WithMany("CollectionWords")
                        .HasForeignKey("UserWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("UserWord");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.GrammarTest", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.GrammarTopic", "GrammarTopic")
                        .WithMany("GrammarTests")
                        .HasForeignKey("GrammarTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTopic");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.TestResult", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.User", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.UserGrammarProgress", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.GrammarTopic", "GrammarTopic")
                        .WithMany("UserGrammarProgresses")
                        .HasForeignKey("GrammarTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnEnglishWebApp.Models.User", "User")
                        .WithMany("GrammarProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrammarTopic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.UserVocabProgress", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.VocabLesson", "VocabLesson")
                        .WithMany("UserProgress")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnEnglishWebApp.Models.User", "User")
                        .WithMany("VocabProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("VocabLesson");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.UserWord", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.User", "User")
                        .WithMany("UserWords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnEnglishWebApp.Models.Dictionary", "Word")
                        .WithMany("UserWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.VocabTest", b =>
                {
                    b.HasOne("LearnEnglishWebApp.Models.VocabLesson", "VocabLesson")
                        .WithMany("VocabTests")
                        .HasForeignKey("VocabLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabLesson");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.Collection", b =>
                {
                    b.Navigation("CollectionWords");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.Dictionary", b =>
                {
                    b.Navigation("UserWords");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.GrammarTopic", b =>
                {
                    b.Navigation("GrammarTests");

                    b.Navigation("UserGrammarProgresses");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.User", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("GrammarProgress");

                    b.Navigation("TestResults");

                    b.Navigation("UserWords");

                    b.Navigation("VocabProgress");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.UserWord", b =>
                {
                    b.Navigation("CollectionWords");
                });

            modelBuilder.Entity("LearnEnglishWebApp.Models.VocabLesson", b =>
                {
                    b.Navigation("UserProgress");

                    b.Navigation("VocabTests");
                });
#pragma warning restore 612, 618
        }
    }
}
